Fix the dictionary client
After 11 years, I finally "fixed" this.

Note: it isn't paginating at all, so the results might be limited.

diff --git a/dict b/dict
--- a/dict
+++ b/dict
@@ -1,32 +1,45 @@
 #!/bin/sh
 
-HTTP_CMD='curl -Ss -H "Host: atilf.atilf.fr" -e "http://atilf.atilf.fr/academie9.htm" -A "Mozilla/5.0 (Windows NT 5.0; rv:5.0) Gecko/20100101 Firefox/5.0"'
-ENDPOINT='http://atilf.atilf.fr/dendien/scripts/generic/'
-
 usage () {
 	echo "usage: $0 <word to define> or $0 -x <regex to search>" >&2
 	exit
 }
 
+fatal () {
+	echo "FATAL: $*. Aborting..."
+	exit 1
+}
+
+html2text () {
+	sed 's/<[^>]*class="[^"]*n-milestone[^"]*"[^>]*>/__/g' \
+	| sed "s/<[^>]*class='[^']*n-milestone[^']*'[^>]*>/__/g" \
+	| sed 's/<[^>]*>//g; s/^null$/Aucun résultat./' | tr _ '\n' | tr -d '"'
+}
+
+checkdep () {
+	command -v "$1" >/dev/null 2>&1 || fatal "Dependency $1 not found"
+}
+
+for dep in curl jq fold; do
+	checkdep $dep || exit $?
+done
+
 [ $# -eq 0 ] && usage
 
-if [[ "$1" != "-x" ]]
+query='{"range":{"begin":0,"end":10},"actions":[]'
+query="$query"',"query":{"maxMatchSize":16000,'
+
+if [ "x$1" != "x-x" ]
 then
-	req=$1
-	regexreq=
+	query="$query"'"input":"match vedettesearch(//orth/hi, EXACT) = '
+        query="$query"'&tokenize(\"'"$1"'\"%cdl) compound(//entryFree) = '
+        query="$query"'vedettesearch"'
 else
-	req=
-	regexreq=$2
+	query="$query"'"input":"match entreeVedetteRegexp(//form/orth) = '
+        query="$query"'&tokenize(\"'"$2"'\" %dc) compound(//entryFree) = '
+        query="$query"'entreeVedetteRegexp"'
 fi
+query="$query"',"modifiers":""},"format":"json+html"}'
 
-# Get a new sid
-sid=$($HTTP_CMD $ENDPOINT/"showps.exe?p=main.txt;host=interface_academie9.txt;java=no;" | sed 's/;/\n/g' | grep -m1 "s=" | sed 's/s=//')
-
-# Here we send the data
-$HTTP_CMD $ENDPOINT/"cherche.exe?15;s="$sid";;" -d "var0="$req"&var2="$regexreq"&var9=*!!*&var11=*!!*&var15=" > /dev/null
-
-# Retrieve the definition, which is bound to the sid, now.
-def=$($HTTP_CMD $ENDPOINT/"affiche.exe?6;s="$sid";d=1;f=255;t=255;r=1;")
-
-# Display the defintion
-echo $def | html2text -unparse -ascii | grep -iv table | grep -iv tr | grep -iv td | grep -iv sultat | sed 's/&amp;#xA0;/<br>/g' | sed 's/&amp;#xAB;/«/g' | sed 's/&amp;#xBB;/»/g' | html2text -width $(tput cols) -style pretty | sed 's/^(/\n(/g'
+echo "$query" | curl -SsL -d@- https://allegro.atilf.fr/repositories/academie9tei/queries/compound | jq '.results[].result' | html2text | fold -s
+echo ""  # newline
